const $=s=>document.querySelector(s); const state=JSON.parse(localStorage.getItem('recoveryState')||'null')||{porn:new Date().toISOString(),drug:new Date().toISOString(),money:0,checkins:[]};
const save=()=>localStorage.setItem('recoveryState',JSON.stringify(state)); let page='today';
const days=s=>Math.max(0,Math.floor((Date.now()-new Date(s))/86400000)); const dh=s=>{let x=Math.max(0,Date.now()-new Date(s)),d=Math.floor(x/86400000),h=Math.floor(x%86400000/3600000);return `${d} DAYS • ${h} HOURS`};
const milestones=[1,3,7,14,30,60,90,180,365];
function counter(name,key){let d=days(state[key]),next=milestones.find(x=>x>d)||365,p=Math.min(100,d/next*100);return `<section class='card'><div class='muted'>${name}</div><div class='counter'>${dh(state[key])}</div><div class='bar'><div class='fill' style='width:${p}%'></div></div><div class='muted small'>Next milestone: ${next} days</div></section>`}
function today(){return `<div class='top'><b>RECOVERY</b><span class='muted'>Private mode</span></div><div class='hero'><div class='muted'>One day at a time</div><h1>Your progress is still yours.</h1></div>${counter('Porn Free','porn')}${counter('Drug Free','drug')}<section class='card sos'><b>Having a difficult moment?</b><p class='muted'>Don't negotiate with the craving. Give yourself ten minutes first.</p><button class='danger' onclick="page='sos';render()">I'M STRUGGLING</button></section><div class='row'><button onclick='checkin()'>CHECK IN</button><button class='secondary' onclick="page='recovery';render()">HOW I FEEL</button></div><section class='card'><b>Today</b><p>You don't have to solve the next year today. Protect the next decision.</p></section>`}
function journey(){let p=days(state.porn),d=days(state.drug);return `<h1>Journey</h1><p class='muted'>Milestones stay in your history even if a streak changes.</p><section class='card'><h3>Porn-free badges</h3>${milestones.map(x=>`<span class='badge ${p>=x?'earned':''}'>${x} day${x>1?'s':''}</span>`).join('')}</section><section class='card'><h3>Drug-free badges</h3>${milestones.map(x=>`<span class='badge ${d>=x?'earned':''}'>${x} day${x>1?'s':''}</span>`).join('')}</section><section class='card'><h3>Manage streaks</h3><label>Porn-free start</label><input type='datetime-local' id='pornDate'><label>Drug-free start</label><input type='datetime-local' id='drugDate'><button onclick='dates()'>SAVE DATES</button></section>`}
function sos(){return `<h1>Get through this moment</h1><section class='card sos center'><div class='big' id='timer'>10:00</div><p>For these ten minutes: don't buy, message, browse or travel toward the trigger.</p><button onclick='timer()'>START 10-MINUTE RESET</button></section><section class='card'><h3>Do this now</h3><p>① Move somewhere different — ideally around other people.</p><p>② Put distance between you and access: close the app/site, leave the room, hand over cash/cards if appropriate.</p><p>③ Drink water and eat something simple if you haven't eaten.</p><p>④ Breathe slowly: in 4 seconds, out 6 seconds, ten times.</p><p>⑤ Message or call someone you trust.</p></section><section class='card'><h3>Name the trigger</h3>${['Stress','Boredom','Loneliness','Sexual trigger','Anger','Withdrawal/craving','Easy access'].map(x=>`<button class='choice' onclick="trigger('${x}')">${x}</button>`).join('')}</section><section class='card'><b>Drug-withdrawal safety</b><p class='muted'>Some withdrawals can require medical care. Severe confusion, seizures, hallucinations, loss of consciousness, breathing problems or other severe symptoms need urgent medical attention. Alcohol and benzodiazepine withdrawal can be particularly dangerous.</p></section>`}
function learn(){return `<h1>Learn</h1><section class='card fact'><h3>Cravings rise and fall</h3><p>A craving can feel like a command, but it is an internal state. Delaying action and changing your environment can help you get through the peak.</p></section><section class='card fact'><h3>Recovery isn't one universal timeline</h3><p>Sleep, appetite, mood, concentration and energy can change after stopping a substance, but timing and severity depend on the drug, pattern of use and the person.</p></section><section class='card fact'><h3>Triggers matter</h3><p>Stress, boredom, cues, locations and routines can become associated with a behaviour. Tracking them helps you plan around patterns instead of relying only on willpower.</p></section><section class='card fact'><h3>A lapse doesn't erase previous progress</h3><p>You can restart a current streak while keeping your history, lessons, total recovery time and achievements.</p></section>`}
function recovery(){return `<h1>How are you feeling?</h1><p class='muted'>Choose what's strongest right now.</p>${['Strong craving','No appetite','Very hungry',"Can't sleep",'Exhausted','Anxious','Irritable / angry','Low mood','Bored','Sexual urge'].map(x=>`<button class='choice' onclick="feeling('${x}')">${x}</button>`).join('')}<section class='card'><h3>Journal</h3><textarea id='journal' rows='5' placeholder="What's happening right now? What triggered it?"></textarea><button onclick='journal()'>SAVE ENTRY</button></section>`}
const pages={today,journey,sos,learn,recovery}; function render(){ $('#app').innerHTML=pages[page](); $('#nav').innerHTML=[['today','⌂','Today'],['journey','◆','Journey'],['sos','!','SOS'],['learn','◉','Learn'],['recovery','↗','Recovery']].map(([p,i,n])=>`<button class='${page===p?'active':''}' onclick="page='${p}';render()"><span class='icon'>${i}</span>${n}</button>`).join(''); if(page==='journey'){let f=x=>new Date(x).toISOString().slice(0,16);$('#pornDate').value=f(state.porn);$('#drugDate').value=f(state.drug)}}
function dates(){state.porn=new Date($('#pornDate').value).toISOString();state.drug=new Date($('#drugDate').value).toISOString();save();render()} function checkin(){state.checkins.push({at:new Date().toISOString(),type:'checkin'});save();alert('Check-in saved.')} function trigger(x){state.checkins.push({at:new Date().toISOString(),trigger:x});save();alert(`Trigger saved: ${x}`)} function feeling(x){state.checkins.push({at:new Date().toISOString(),feeling:x});save();alert(`${x} saved. Look for patterns over time.`)} function journal(){let v=$('#journal').value.trim();if(v){state.checkins.push({at:new Date().toISOString(),journal:v});save();$('#journal').value='';alert('Journal entry saved.')}} function timer(){let n=600;clearInterval(window.t);window.t=setInterval(()=>{n--;let el=$('#timer');if(!el)return clearInterval(window.t);el.textContent=`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;if(n<=0){clearInterval(window.t);el.textContent='YOU MADE 10 MINUTES';}},1000)}
render(); setInterval(()=>{if(page==='today')render()},60000);

// V2 enhancements
state.settings=state.settings||{substance:'Not set',dailyCost:0,privacyLock:false};state.reasons=state.reasons||[];save();
const oldToday=today, oldRecovery=recovery;
today=function(){let base=oldToday();let clean=days(state.drug), saved=(clean*(+state.settings.dailyCost||0)).toFixed(2);return base+`<section class='card'><h3>Progress snapshot</h3><div class='grid'><div class='stat'><span class='muted'>Check-ins</span><b>${state.checkins.length}</b></div><div class='stat'><span class='muted'>Estimated saved</span><b>£${saved}</b></div></div></section><section class='card assistant'><h3>Recovery Assistant</h3><div id='chat' class='chat'><div class='bubble'>Tell me what is happening right now. Try “I’m craving”, “I can’t sleep”, or “remind me why I quit”.</div></div><div class='row'><input id='aiq' placeholder='Talk to me…'><button onclick='askAI()'>SEND</button></div></section><section class='card'><h3>My reasons</h3>${state.reasons.length?state.reasons.map(r=>`<span class='pill'>${r}</span>`).join(''):`<p class='muted'>Add reasons you want to protect when cravings hit.</p>`}<div class='row'><input id='reason' placeholder='e.g. My health, money, focus'><button onclick='addReason()'>ADD</button></div></section>`}
recovery=function(){return oldRecovery()+`<section class='card'><h3>Drug recovery setup</h3><label>Substance / category</label><select id='substance'><option>Not set</option><option>Cannabis</option><option>Cocaine / stimulants</option><option>Opioids</option><option>Alcohol</option><option>Benzodiazepines</option><option>Other / multiple</option></select><label>Approx. previous spend per day (£)</label><input id='cost' type='number' min='0' step='0.01' value='${state.settings.dailyCost||0}'><button onclick='saveRecoverySetup()'>SAVE</button><p class='muted small'>This app does not diagnose withdrawal. Alcohol and benzodiazepine withdrawal can be medically dangerous; seek professional medical advice rather than relying on an app to manage it.</p></section><section class='card'><h3>Your recent patterns</h3>${recentPatterns()}</section>`}
function recentPatterns(){let a=state.checkins.slice(-10).reverse();return a.length?a.map(x=>`<p><span class='muted'>${new Date(x.at).toLocaleDateString()}</span> — ${x.feeling||x.trigger||x.journal||'Check-in'}</p>`).join(''):`<p class='muted'>Your check-ins will appear here.</p>`}
function addReason(){let e=$('#reason'),v=e&&e.value.trim();if(v){state.reasons.push(v);save();render()}}
function saveRecoverySetup(){state.settings.substance=$('#substance').value;state.settings.dailyCost=+$('#cost').value||0;save();alert('Recovery settings saved.');render()}
function askAI(){let e=$('#aiq');if(!e||!e.value.trim())return;let q=e.value.trim(),l=q.toLowerCase(),r;if(/crav|relaps|use|porn/.test(l))r="Don't act on the urge yet. Open SOS and give yourself ten minutes. Move away from access, change rooms, and contact someone safe if you can.";else if(/sleep/.test(l))r="Sleep disruption can happen during behaviour change or substance recovery. Keep tonight simple: reduce stimulation, hydrate, and avoid using a substance to force sleep. Severe or concerning withdrawal symptoms need medical advice.";else if(/why|reason/.test(l))r=state.reasons.length?`You told me these reasons matter: ${state.reasons.join(', ')}.`:"Add your reasons on the Today page so I can bring them back when you need them.";else if(/eat|appetite|hungry/.test(l))r="Appetite can change during recovery. Aim for something manageable and regular rather than waiting to feel perfect—fluids and simple food can be easier. Persistent inability to eat or drink needs medical advice.";else r="I hear you. Name the strongest feeling or trigger right now, then choose the smallest action that puts distance between you and the old behaviour for the next ten minutes.";let c=$('#chat');c.innerHTML+=`<div class='bubble me'>${escapeHtml(q)}</div><div class='bubble'>${r}</div>`;c.scrollTop=c.scrollHeight;e.value=''}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
const oldRender=render;render=function(){oldRender();if(page==='recovery'&&$('#substance'))$('#substance').value=state.settings.substance||'Not set'}
render();

// V3 — private progress history, relapse reflection, lock, notifications and backend-ready AI
state.version=3;
state.history=state.history||[];
state.settings.pin=state.settings.pin||'';
state.settings.notifications=state.settings.notifications||false;
save();

function logLapse(kind){
  if(!confirm(`Log a ${kind} lapse and restart only this current streak? Your badges and history stay recorded.`)) return;
  const note=prompt('Optional: what happened just before it?')||'';
  const key=kind==='porn'?'porn':'drug';
  state.history.push({at:new Date().toISOString(),kind,previousStart:state[key],note});
  state[key]=new Date().toISOString(); save(); render();
}
function historyCard(){
  let rows=state.history.slice(-8).reverse().map(x=>`<div class='historyRow'><div><b>${x.kind==='porn'?'Porn':'Drug'} reset</b><div class='muted small'>${new Date(x.at).toLocaleString()}</div></div><span>${escapeHtml(x.note||'Logged')}</span></div>`).join('');
  return `<section class='card'><h3>Progress history</h3>${rows||`<p class='muted'>No resets logged. Your history will stay here without erasing earlier progress.</p>`}</section>`;
}
function insights(){
  let recent=state.checkins.slice(-30), counts={}; recent.forEach(x=>{let k=x.trigger||x.feeling;if(k)counts[k]=(counts[k]||0)+1});
  let top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,3);
  return `<section class='card'><h3>Patterns</h3>${top.length?top.map(([k,v])=>`<div class='metric'><span>${escapeHtml(k)}</span><b>${v}×</b></div>`).join(''):`<p class='muted'>Keep checking in and this page will surface your recurring triggers and feelings.</p>`}</section>`;
}
function settingsPanel(){return `<section class='card'><h3>Privacy & reminders</h3><label>App PIN (optional)</label><input id='pinSet' inputmode='numeric' maxlength='6' placeholder='4–6 digits' value='${escapeHtml(state.settings.pin||'')}'><button onclick='savePin()'>SAVE PIN</button><button class='secondary' onclick='enableNotifications()'>${state.settings.notifications?'REMINDERS ENABLED':'ENABLE DAILY REMINDERS'}</button><p class='muted small'>When signed in, your records sync through your Hub account. The optional PIN is a screen lock, not encryption. You can export a local backup below.</p></section>`}
function savePin(){let p=$('#pinSet').value.trim();if(p && !/^\d{4,6}$/.test(p))return alert('Use 4–6 digits, or leave it blank to disable the PIN.');state.settings.pin=p;save();alert(p?'PIN saved. It will be requested when the app is reopened.':'PIN disabled.');}
async function enableNotifications(){if(!('Notification'in window))return alert('Notifications are not supported in this browser.');let p=await Notification.requestPermission();state.settings.notifications=p==='granted';save();alert(state.settings.notifications?'Reminders are enabled. Install the app to your Home Screen for the best iPhone experience.':'Notification permission was not granted.');render()}
function lockGate(){if(!state.settings.pin||sessionStorage.getItem('recoveryUnlocked')==='1')return;document.body.insertAdjacentHTML('beforeend',`<div id='lockGate' class='lockGate'><div class='lockBox'><div class='lockMark'>R</div><h2>Recovery is locked</h2><p class='muted'>Enter your private PIN.</p><input id='unlockPin' type='password' inputmode='numeric' maxlength='6' placeholder='••••'><button onclick='unlockApp()'>UNLOCK</button></div></div>`)}
function unlockApp(){if($('#unlockPin').value===state.settings.pin){sessionStorage.setItem('recoveryUnlocked','1');$('#lockGate').remove()}else alert('Incorrect PIN.')}

const v2Journey=journey, v2Recovery=recovery;
journey=function(){return v2Journey()+`<section class='card'><h3>Log without losing your story</h3><p class='muted'>A reset changes the current streak only. Your earlier milestones and history remain part of your recovery.</p><div class='row'><button class='secondary' onclick="logLapse('porn')">LOG PORN LAPSE</button><button class='secondary' onclick="logLapse('drug')">LOG DRUG LAPSE</button></div></section>`+historyCard()}
recovery=function(){return v2Recovery()+insights()+settingsPanel()}

// Backend-ready assistant: uses /api/recovery-chat when deployed with a server; falls back safely offline.
const localAskAI=askAI;
askAI=async function(){
  let e=$('#aiq'); if(!e||!e.value.trim())return; let q=e.value.trim();
  let c=$('#chat'); c.innerHTML+=`<div class='bubble me'>${escapeHtml(q)}</div><div class='bubble' id='thinking'>Thinking…</div>`; e.value=''; c.scrollTop=c.scrollHeight;
  try{
    let res=await fetch('/api/recovery-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,context:{reasons:state.reasons,substance:state.settings.substance,recent:state.checkins.slice(-8)}})});
    if(!res.ok)throw 0; let data=await res.json(); $('#thinking').remove(); c.innerHTML+=`<div class='bubble'>${escapeHtml(data.reply||'')}</div>`;
  }catch(_){ $('#thinking').remove(); $('#aiq').value=q; localAskAI(); }
}

const v3Render=render; render=function(){v3Render();}; render(); lockGate();

// V4 — account/cloud-ready architecture, export/import, notification registration, central-AI handoff
state.version=4; state.settings.cloud=state.settings.cloud||false; state.settings.accountEmail=state.settings.accountEmail||''; save();
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='recovery-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importData(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{try{let x=JSON.parse(await i.files[0].text());if(!x.porn||!x.drug)throw 0;Object.keys(state).forEach(k=>delete state[k]);Object.assign(state,x);state.version=4;save();alert('Backup restored.');location.reload()}catch(e){alert('That backup could not be restored.')}};i.click()}
async function cloudSync(){if(!state.settings.cloud)return alert('Cloud sync is not connected yet. Configure the V4 server and sign in first.');try{let r=await fetch('/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state})});if(!r.ok)throw 0;let d=await r.json();if(d.state){Object.assign(state,d.state);save();render()}alert('Sync complete.')}catch(e){alert('Cloud server is unavailable. Your local data is safe and unchanged.')}}
async function connectAccount(){let email=prompt('Email for your Recovery account:');if(!email)return;try{let r=await fetch('/api/auth/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});if(!r.ok)throw 0;state.settings.accountEmail=email;state.settings.cloud=true;save();alert('Account connection started. In production, verify the sign-in link/code sent by your configured auth provider.');render()}catch(e){alert('No V4 backend is connected yet. Local mode remains active.')}}
function v4Panel(){return `<section class='card'><h3>Your data</h3><p class='muted small'>Your changes save on this device and sync when you are signed in to the Hub. The optional PIN only locks this screen; it does not encrypt your records.</p><div class='stack'><button class='secondary' onclick='exportData()'>EXPORT BACKUP</button><button class='secondary' onclick='importData()'>RESTORE BACKUP</button></div></section>`}
const v4Recovery=recovery; recovery=function(){return v4Recovery()+v4Panel()}
render();
