/* Life Manager weekly 24-hour schedule system */
(() => {
  const WEEK_KEY = 'kb-life-manager-week-v2';
  const templates = {
    night:{name:'🌙 Night Shift',anchor:'Work starts',mode:'night',work:12,items:[[-150,-120,'Wake + water'],[-120,-90,'Bella walk + food'],[-90,-30,'Meal / get ready'],[-30,0,'Commute to work'],[0,720,'WORK — NIGHT SHIFT'],[720,750,'Commute home'],[750,790,'Bella walk + food'],[790,825,'Shower + meal'],[825,840,'Wind down'],[840,1290,'SLEEP'],[1290,1320,'Wake / water'],[1320,1410,'Personal time'],[1410,1440,'Prepare for work']]},
    early:{name:'🌅 Early Shift',anchor:'Work starts',mode:'normal',work:12,items:[[-130,-125,'Wake + water'],[-125,-115,'Meditation'],[-115,-75,'Bella walk + food'],[-75,-45,'Shower + breakfast'],[-45,-30,'Final work check'],[-30,0,'Commute to work'],[0,720,'WORK — EARLY SHIFT'],[720,750,'Commute home'],[750,790,'Bella walk + food'],[790,830,'Dinner / shower'],[830,900,'Wind down'],[900,1310,'SLEEP'],[1310,1440,'Wake / prepare for day']]},
    day:{name:'☀️ Day Shift',anchor:'Work starts',mode:'normal',work:8,items:[[-150,-140,'Wake + water'],[-140,-125,'Meditation'],[-125,-85,'Bella walk + food'],[-85,-55,'Breakfast + shower'],[-55,-30,'Get ready'],[-30,0,'Commute'],[0,480,'WORK — DAY SHIFT'],[480,510,'Commute home'],[510,555,'Bella walk + food'],[555,645,'Gym / exercise'],[645,705,'Dinner + shower'],[705,900,'Projects / free time'],[900,960,'Wind down'],[960,1410,'SLEEP'],[1410,1440,'Wake buffer']]},
    late:{name:'🌆 Late Shift',anchor:'Work starts',mode:'normal',work:8,items:[[-360,-350,'Wake + water'],[-350,-335,'Meditation'],[-335,-295,'Bella walk + food'],[-295,-235,'Breakfast / shower'],[-235,-145,'Gym / exercise'],[-145,-75,'Meal + personal admin'],[-75,-30,'Get ready'],[-30,0,'Commute'],[0,480,'WORK — LATE SHIFT'],[480,510,'Commute home'],[510,550,'Bella walk + food'],[550,600,'Meal / shower'],[600,630,'Wind down'],[630,1080,'SLEEP']]},
    off:{name:'🏠 Off Day',anchor:'Day starts',mode:'open',items:[[0,15,'Wake + water'],[15,30,'Meditation'],[30,75,'Bella walk + food'],[75,120,'Breakfast + shower'],[120,240,'Important task / life admin'],[240,300,'Break / lunch'],[300,420,'Gym / exercise'],[420,540,'Project / errands'],[540,600,'Free time'],[600,645,'Bella walk + food'],[645,720,'Dinner'],[720,900,'Free time / social'],[900,960,'Wind down'],[960,1410,'SLEEP'],[1410,1440,'Wake buffer']]},
    recovery:{name:'😴 Recovery Day',anchor:'Day starts',mode:'open',items:[[0,15,'Wake gently + water'],[15,60,'Bella walk + food'],[60,120,'Meal + shower'],[120,240,'Low-demand free time'],[240,300,'One small life-admin task'],[300,420,'Rest / nap if needed'],[420,540,'Fresh air / gentle movement'],[540,585,'Bella walk + food'],[585,660,'Dinner'],[660,900,'Low-stimulation free time'],[900,960,'Wind down'],[960,1410,'SLEEP'],[1410,1440,'Wake buffer']]},
    project:{name:'🔧 Project Day',anchor:'Day starts',mode:'open',items:[[0,15,'Wake + water'],[15,60,'Bella walk + food'],[60,105,'Breakfast + shower'],[105,225,'Project focus block 1'],[225,255,'Break'],[255,375,'Project focus block 2'],[375,435,'Lunch'],[435,555,'Project focus block 3'],[555,600,'Reset / tidy'],[600,645,'Bella walk + food'],[645,720,'Dinner'],[720,870,'Free time'],[870,930,'Plan tomorrow / wind down'],[930,1380,'SLEEP'],[1380,1440,'Wake buffer']]},
    reset:{name:'🧘 Reset Day',anchor:'Day starts',mode:'open',items:[[0,15,'Wake + water'],[15,30,'Meditation'],[30,75,'Bella walk + food'],[75,120,'Breakfast + shower'],[120,210,'Home reset / laundry'],[210,300,'Life admin'],[300,360,'Lunch / break'],[360,450,'Weekly planning'],[450,540,'Walk / exercise'],[540,585,'Bella walk + food'],[585,660,'Dinner'],[660,780,'Prepare week / clothes / food'],[780,900,'Free time'],[900,960,'Wind down'],[960,1410,'SLEEP'],[1410,1440,'Wake buffer']]}
  };
  const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
  const fullDays=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
  let weekly = loadWeek();
  function loadWeek(){try{return JSON.parse(localStorage.getItem(WEEK_KEY))||{}}catch{return {}}}
  function saveWeek(){localStorage.setItem(WEEK_KEY,JSON.stringify(weekly));}
  function mondayOf(dateStr){const d=new Date(dateStr+'T12:00:00'),n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)}
  function datePlus(dateStr,n){const d=new Date(dateStr+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
  function minsToTime(m){m=((m%1440)+1440)%1440;return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
  function templateTasks(t,anchor){const a=toMinutes(anchor);return t.items.map(([s,e,title])=>[minsToTime(a+s),minsToTime(a+e),title,[],title.includes('SLEEP')?'Protect this sleep block.':'']);}
  const originalGetTasks=getTasks;
  getTasks=function(d){if(d.template&&templates[d.template])return templateTasks(templates[d.template],d.anchor||defaultAnchor(d.template));return originalGetTasks(d)};
  function defaultAnchor(k){return {night:'22:00',early:'06:00',day:'09:00',late:'14:00',off:'08:00',recovery:'10:00',project:'08:00',reset:'09:00'}[k]||'08:00'}
  function applyDay(date,key,anchor){const old=selectedDate;selectedDate=date;const d=dayState();d.template=key;d.anchor=anchor;d.mode=templates[key].mode;d.actualFinish=null;saveState();selectedDate=old;}
  function buildChooser(){const box=document.querySelector('#modeChooser');if(!box)return;const mon=mondayOf(selectedDate);box.innerHTML=`<div class="week-planner-head"><p class="eyebrow">SET THE WEEK ONCE</p><h1>What kind of week is it?</h1><p>Choose a 24-hour template and its start time for each day. You can change any day later.</p></div><div class="week-days">${days.map((d,i)=>{const date=datePlus(mon,i),saved=weekly[date]||{},key=saved.template||((i<5)?'night':'off'),anchor=saved.anchor||defaultAnchor(key);return `<article class="week-day ${date===selectedDate?'selected':''}" data-week-date="${date}"><strong>${d}</strong><small>${date.slice(5)}</small><select class="week-template" aria-label="${d} template">${Object.entries(templates).map(([k,t])=>`<option value="${k}" ${k===key?'selected':''}>${t.name}</option>`).join('')}</select><label><span class="anchor-label">${templates[key].anchor}</span><input class="week-anchor" type="time" value="${anchor}"></label></article>`}).join('')}</div><div class="week-actions"><button class="primary-button" id="applyWeek" type="button">Save & apply week</button><button class="secondary-button" id="useTodayOnly" type="button">Apply selected day</button></div>`;
    box.querySelectorAll('.week-template').forEach(sel=>sel.addEventListener('change',e=>{const card=e.target.closest('.week-day'),key=e.target.value;card.querySelector('.anchor-label').textContent=templates[key].anchor;card.querySelector('.week-anchor').value=defaultAnchor(key)}));
    box.querySelectorAll('.week-day').forEach(card=>card.addEventListener('click',e=>{if(e.target.matches('select,input'))return;box.querySelectorAll('.week-day').forEach(x=>x.classList.remove('selected'));card.classList.add('selected')}));
    document.querySelector('#applyWeek').onclick=()=>{box.querySelectorAll('.week-day').forEach(card=>{const date=card.dataset.weekDate,key=card.querySelector('.week-template').value,anchor=card.querySelector('.week-anchor').value||defaultAnchor(key);weekly[date]={template:key,anchor};applyDay(date,key,anchor)});saveWeek();renderAll();toast('Week saved — schedules ready');};
    document.querySelector('#useTodayOnly').onclick=()=>{const card=box.querySelector('.week-day.selected')||box.querySelector(`[data-week-date="${selectedDate}"]`),date=card.dataset.weekDate,key=card.querySelector('.week-template').value,anchor=card.querySelector('.week-anchor').value||defaultAnchor(key);weekly[date]={template:key,anchor};saveWeek();applyDay(date,key,anchor);if(date===selectedDate)renderAll();toast('Schedule applied');};
  }
  const originalRenderToday=renderToday;
  renderToday=function(){const d=dayState();if(!d.mode&&weekly[selectedDate]){applyDay(selectedDate,weekly[selectedDate].template,weekly[selectedDate].anchor)}originalRenderToday();d.template&&enhanceToday(d);if(!d.mode)buildChooser();};
  function enhanceToday(d){const t=templates[d.template];if(!t)return;document.querySelector('#modeEyebrow').textContent=`${t.name.replace(/^\S+\s/,'').toUpperCase()} · START ${d.anchor}`;document.querySelector('#routineHeading').textContent=`${t.name} · 24-hour schedule`;document.querySelector('#finishCard').hidden=true;let change=document.querySelector('#changeWeekSchedule');if(!change){change=document.createElement('button');change.id='changeWeekSchedule';change.className='secondary-button change-week';change.type='button';change.textContent='Change weekly schedule';document.querySelector('#nowCard')?.before(change);change.onclick=()=>{const d=dayState();d.mode=null;saveState();document.querySelector('#dayWorkspace').hidden=true;document.querySelector('#modeChooser').hidden=false;buildChooser();window.scrollTo({top:0,behavior:'smooth'})};}}
  const css=document.createElement('style');css.textContent=`.week-days{display:grid;grid-template-columns:repeat(7,minmax(120px,1fr));gap:10px;margin-top:18px;overflow-x:auto;padding-bottom:8px}.week-day{border:1px solid var(--line,#33415f);border-radius:16px;padding:12px;display:grid;gap:8px;min-width:130px;background:rgba(255,255,255,.035)}.week-day.selected{outline:2px solid #75a7ff}.week-day strong{font-size:1rem}.week-day small{opacity:.65}.week-day select,.week-day input{width:100%;box-sizing:border-box;border-radius:10px;padding:9px;background:#111a2e;color:inherit;border:1px solid #405071}.week-day label{display:grid;gap:4px;font-size:.72rem}.week-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.change-week{margin:0 0 14px}.week-planner-head p{max-width:680px}@media(max-width:720px){.week-days{grid-template-columns:repeat(7,145px);scroll-snap-type:x proximity}.week-day{scroll-snap-align:start}.week-actions>*{flex:1 1 160px}}`;document.head.appendChild(css);
  document.addEventListener('DOMContentLoaded',()=>{setTimeout(()=>{const d=dayState();if(!d.mode)buildChooser();else if(d.template)enhanceToday(d)},0)});
})();